### PR TITLE
Add flags to make windows linking and extraction invisible

### PR DESCRIPTION
**Pull request by clinton-hall**
Trying again on nightly branch... I'll fix the Posix handling there

### CODE REVIEW

**Comment by clinton-hall** [comment]
@Jaerin Thanks for your work... Sorry for all the messing about with Pullrequests (I sent one the wrong way... to your fork!

I'll make a small change in my nightly to allow this to work with POSIX again... watch for the changes ;)

**Comment by clinton-hall** [comment]
See the changes in the last commit linked above...

I have now rebased and put this into Master etc...

As some users appear to be using your fork... it might be worth trying to sync up with my master branch again so that way they can git pull and be working again :)

**Comment by Jaerin** [comment]
I think I should be resynced back into the main branch.  Let me know if there is something else I need to do.

**Comment by clinton-hall** [comment]
hmm... my recent changes don't appear in your fork...
I'm not sure exactly how to sync repositories, particularly when there a merge commits etc... (as it was I had to do some rebasing to get my dev branch back in sync)

**Comment by Jaerin** [comment]
Huzzah!  It worked....seems like no one using git understands how it is supposed to work :)

Had to checkout your upstream branch and then push it to mine.

**Comment by clinton-hall** [comment]
Glad you got it to work...
I must admit, I don't understand half of the capabilities of git... I learn as I go, and do a lot of searching at stackoverflow.com ;)

**Pull request merged**
