### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by clinton-hall**

### CODE REVIEW

**Comment by clinton-hall** [comment]
@labrys 
ok... so i have some form of checking going on.

##[warning]No test result files matching **/test-results.xml were found.
so, presumably we need to define what test results we want?

All failures are the same:
```
##[section]Starting: Install dependencies
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.146.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
Generating script.
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:3864) Warning: Use Cipheriv for counter mode of aes-256-ctr
Script contents:
python -m pip install --upgrade pip && pip install -r requirements.txt
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/7140c9ea-b929-4838-ad98-319e9051fa51.sh
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 19.0.2
    Uninstalling pip-19.0.2:
      Successfully uninstalled pip-19.0.2
Successfully installed pip-19.0.3
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
##[error]Bash exited with code '1'.
##[section]Finishing: Install dependencies
```

I'm not sure how much access you have to the azure pipeline itself, as this has linked back to my Microsoft account...

**Comment by clinton-hall** [comment]
ok, this is actually looking good. 
The issue now is that the tests/general.py is setup to run on my system with a Sick* fork running (along with other tests)....

**Comment by clinton-hall** [comment]
@labrys 
So, it looks like I've been barking up the wrong tree.... this isn't testing that the specified test scripts are executed without errors, but it requires a series of test asserts and raises...

also, I think python 3.7 testing needs to be removed as several libs are not currently py3.7 compatible.

Also, I haven't checked yet if there is any easy way of setting up test downloaders and media managers to test the interfaces to.

**Comment by clinton-hall** [comment]
@labrys 

forget all of the stupid changes I made until I finally figured it out... (this is all very new to me)

As it is, this Azure Pipeline (which I have hopefully added you to) should test that the scripts build on all python versions.
It then runs any test*.py script. In there we can assert any checks we want verified.
In this case the single script I have added basically verifies that we can import the modules etc, then tests that we can read a single parameter...

Early days in terms of testing, but this should mean automated verification instead of me trying to run the scripts on my NAS after each change.

**Comment by labrys** [comment]
Sorry I wasn't on when you were working on this or I could have saved you some headaches :).   I haven't used Azure Pipelines yet for CI, but am very familiar with using Travis and AppVeyor.  I'm sure Azure Pipelines isn't much different.

As you have correctly determined, you normally have a test folder structure that contains your tests in multiple python files (each with the name containing `test` and usually at the beginning although this is configurable).  

Each test file can have one or more tests in it (also containing the word `test` in the function name).  

Each individual test function should be responsible for testing some functionality using various parameters.  

A test runner like pytest will discover all the tests and run them.

A tox configuration can be used to choose how the test runner will run test suite.  For example running the tests on each supported version of python.

A CI like Azure Pipelines can be configured to run the tests with your test runner (e.g. pytest, tox, etc)
If any tests fail, the CI server will fail the build.

Github can be configured to only allow a PR to be merged if all tests pass.

**Pull request merged**
