### PR TITLE
DownloadedMovieScan updated to DownloadedMoviesScan

### PR DESCRIPTION
**Pull request by sugarfunk**
Radarr devs updated API from DownloadedMovieScan to DownloadedMoviesScan
https://github.com/Radarr/Radarr/issues/1123

### CODE REVIEW

**Comment by clinton-hall** [comment]
Thanks! Appreciate the PR.

**Comment by breezytm** [comment]
I can't get it to work. I am still getting the 500 error

```
FO	Sun Mar 26 2017 12:56:05	Collection Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n added to history
ERROR	Sun Mar 26 2017 12:56:05	Post-process-script nzbToMedia/nzbToRadarr.py for Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n failed
INFO	Sun Mar 26 2017 12:56:05	nzbToRadarr: Radarr: Failed to post-process - Server returned status 500!
INFO	Sun Mar 26 2017 12:56:05	nzbToRadarr: [12:56:05] [ERROR]::MAIN: A problem was reported in the /share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/nzbToMedia/nzbToRadarr.py script.
INFO	Sun Mar 26 2017 12:56:05	nzbToRadarr: [12:56:05] [ERROR]::RADARR: Server returned status 500
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::RADARR: Opening URL: http://localhost:7878/api/command with PARAMS: {'path': '/share/Download/nzbget/dst/movies/Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n', 'name': 'DownloadedMoviesScan', 'downloadClientId': '0fd54a79a10f474cb8045442836cb774'}
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [INFO]::TRANSCODER: SUCCESS: [Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n.mkv] has no corruption.
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::MAIN: calling command: /share/MD0_DATA/.qpkg/NZBGet/repository/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /share/Download/nzbget/dst/movies/Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n/Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n.mkv
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [INFO]::TRANSCODER: Checking [Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n.mkv] for corruption, please stand by ...
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::MAIN: calling command: /share/MD0_DATA/.qpkg/NZBGet/repository/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /share/MD0_DATA/Download/nzbToMedia/tests/test.mp4
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::SERVER: Server responded at http://localhost:7878/api/command
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:7878/api/command
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [WARNING]::MAIN: Unable to find a imdbID for Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [ERROR]::MAIN: No imdbID returned from omdbapi.com
INFO	Sun Mar 26 2017 12:56:04	nzbToRadarr: [12:56:04] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Searching IMDB for imdbID ...
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Attemping imdbID lookup for Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Calling Radarr:movie2 to post-process:Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Auto-detected SECTION:Radarr
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: Adding NZB download info for directory /share/Download/nzbget/dst/movies/Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n to database
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: Script triggered from NZBGet Version 17.1.
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/nzbToMedia/nzbToRadarr.py']
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: #########################################################
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: #########################################################
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: nzbToMedia Version:cabaa9950c368edb5afa70797a0fbae2a8d7f8e6 Branch:nightly (Linux 3.4.6)
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [INFO]::MAIN: No update needed
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: cur_commit = cabaa9950c368edb5afa70797a0fbae2a8d7f8e6 % (newest_commit)= cabaa9950c368edb5afa70797a0fbae2a8d7f8e6, num_commits_behind = 0, num_commits_ahead = 0
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:03	nzbToRadarr: [12:56:03] [DEBUG]::MAIN: git fetch origin : returned successful
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Executing git fetch origin with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [INFO]::MAIN: Checking if git needs an update
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Using: git
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: git version : returned successful
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Executing git version with your shell in /share/MD0_DATA/Download/nzbToMedia
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Checking if we can use git commands: git version
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	Sun Mar 26 2017 12:56:02	nzbToRadarr: [12:56:02] [INFO]::MAIN: Checking database structure...
INFO	Sun Mar 26 2017 12:55:57	Executing post-process-script nzbToMedia/nzbToRadarr.py for Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
INFO	Sun Mar 26 2017 12:55:57	Queueing Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n for post-processing
INFO	Sun Mar 26 2017 12:55:57	Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n returned from history back to download queue
INFO	Sun Mar 26 2017 12:55:57	Post-processing again Star.Wars.Episode.VII.The.Force.Awakens.2015.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT-Chamele0n
```

**Comment by sugarfunk** [comment]
@breezytm are you on the nightly/development builds for Radarr? You need to be on their nightly

**Comment by breezytm** [comment]
I am actually on nightly

**Comment by sugarfunk** [comment]
@breezytm sorry, I meant the nightly builds for Radarr. Not NZBtoMedia.

In Radarr, Change branch to 'nightly' in settings > General > show advanced settings > branch

**Comment by breezytm** [comment]
@sugarfunk Yeah you did say that. I simply misread what you wrote. But hey, thanks. Things are working right now with the nightly. Thanks

**Pull request merged**
