### PR TITLE
Added Bitrate for MKV SD and Option for resolution

### PR DESCRIPTION
**Pull request by bbsan2k**
I added a default Bitrate for MKV-SD because of poor transcoding quality for some releases.

In order to evaluate the parameters I also added a field for Resolution in the config.

### CODE REVIEW

**Comment by clinton-hall** [comment]
Thanks. Just curious how the video resolution works? you have added it into the nzbget config section, but this isn't passed into the config itself...???

https://github.com/clinton-hall/nzbToMedia/blob/nightly/core/nzbToMediaConfig.py#L412-L431

this is where all transcoder sections are called in from NZBGet environment...

**Comment by bbsan2k** [comment]
Isn't this handled by:
https://github.com/clinton-hall/nzbToMedia/blob/nightly/core/__init__.py#L501
?
Maybe I got this wrong. Going to test this once again!

**Comment by bbsan2k** [comment]
` MAIN: calling command: nice -n10 ionice -c2 -n4 /usr/local/bin/ffmpeg -loglevel warning -fflags +genpts -i /downloads/completed/Series/********.mkv -map 0:0 -map 0:1 -map 0:1 -c:v libx264 -r 24.0 -vf scale=720:404 -b:v 800000 -preset medium -crf 19 -level 3.1 -c:a:0 aac -strict -2 -b:a:0 160000 -c:a:1 copy -sn -movflags +faststart /downloads/completed/Series/********-transcoded.mkv
`
Looks like it's working now ;)

**Comment by clinton-hall** [comment]
The _init_.py is where the config file is read and the option is written into the core... you are right on that and that all works fine..

The nzbToMediaConfig.py is where the options are read from nzbGet and written into the config... by default this will over-write anything in the config already...

Looks like it is all good now. Thanks.

**Pull request merged**
