### PR TITLE
Code cleanup core

### PR DESCRIPTION
**Pull request by labrys**
##### DESCRIPTION

This PR focuses on code clean-up more of `core/*`.

While the majority of this PR is just code cleanup for things like PEP8 compliance, the important commits are the following:

##### IMPORTANT CHANGE LIST:
* 3acaf29 Update `six` to 1.10.0
* 382d108 Optimize imports
 * PEP8: Fix module level import not at top of file
 * Remove unused imports
 * Remove `simplejson`
 * Replace `mimetools` with `email`
* eb1ee8b `set` expected, but passing `list`
* Python 2/3 compatibility
 * cf1ae93 Use `six` to standardize imports
 * d4e5809 Use `print_function` to standardize printing
 * abf63d6 Use `six.iteritems` helper to standardizes `dict.iteritems`
 * ec2fc8d Use `six.text_type` to standardize `unicode` function
 * 5903538 Make `long = int` in Python 3
 * ec71e78 Convert `except ExceptionClass, Target:` to `except ExceptionClass as Target:`
 * 8434fd5 Fix relative imports
 * 22daf02 `raise` with no arguments can only be used in an `except` block
* df8c6bc Too broad exceptions: Use `.get()` with default value instead.

##### REMAINING CHANGE LIST:
* Add encoding declaration
* Convert to new-style class by inheriting from `object`
* PEP8: Fix formatting
 * Remove redundant backslash between brackets
 * Fix multiple statements on one line
 * Fix missing/excess whitespace
 * Fix comments not starting with a single `#` and a space
 * Convert tabs to spaces
 * Use triple-quoted docstring
* PEP8: Tests for membership should use `in`/`not in`
* PEP8: comparison to `None`, `True`, or `False` should use `is`/`is not`
* PEP8: `.has_key()` is deprecated, use `in`
* Streamline conditional statements
 * Non-zero `int` evaluate True.
* Code cleanup
 * Streamline variable assignment
 * Replace assignment with augmented assignment
 * Remove unused variables and redundant parentheses
* Rewrite dictionary creation as a dictionary literal
* Use `format()` instead of `%` for string formatting

Note: This PR already includes #1048

### CODE REVIEW

**Comment by clinton-hall** [comment]
Amazing work.
As you can probably tell, style/formatting is not my strength... heck, I have no formal training and just "fell" into this project.

I hope, despite my somewhat complex (and probably not overly logical) flow etc you have been able to follow what the code is doing. I am the first to say this project has somewhat surpassed my skills. In fact that whole transcoder thing (with the 7zip passing the vobs from inside the iso, through stdout-stdin, to ffmpeg) still takes me for ever to try and figure out what is going on ;)

**Comment by clinton-hall** [comment]
I just added you as a collaborator if you want to add directly into the repository. Please don't take this as me expecting you to do more... rather an offer to allow you make make changes directly if you have more that you wish to contribute.

**Comment by labrys** [comment]
I appreciate it. I'm working on some more cleanup and trying to get this Python 3 compatible.  A couple words of note/warning its possible (and probably likely) that some of these changes will raise some exceptions that weren't previously being raised, however dealing with them when they arise should be fairly easy.  I also expect potential issues with other config sections that should be resolved by applying fixes like #1048 or fully rewriting the config.

**Comment by clinton-hall** [comment]
Yeah no doubt... I have broken the code a few times...

I just realised this is all being merged into dev branch. If I merge it all into nightly branch, can you make further changes in nightly (smallest user base), then we can merge back up to dev and then master?

**Comment by clinton-hall** [comment]
Actually, on my end
```
Traceback (most recent call last):
  File "./nzbToMedia.py", line 503, in <module>
    import core
  File "/volume1/Public/test/nzbToMedia/core/__init__.py", line 13, in <module>
    from six.moves import reload_module
ImportError: No module named six.moves
```
I perform a manual run of ./TorrentToMedia.py and ./nzbToMedia.py before committing... My logic being that even if the deeper code fails, as long as the manual reun goes to completion, the auto-update should work and no-one will be stuck  (some users struggle with ssh and git etc).

Looking at the above, it appears the updated six is not loading correctly?

**Comment by clinton-hall** [comment]
I should add, I run this on a NAS with a very stripped-down and basic Python2.7 (so no included six modules). This therefore only loads the "six" modules bundled with nzbToMedia

**Comment by clinton-hall** [comment]
Found it...
https://github.com/clinton-hall/nzbToMedia/commit/f093fafd8d1b7c5ee0412fd67e2a266762f0737a

I merged this in to nightly and dev.
There may be a neater method. But basically I leave all of the built-in lib imports until after the path is extended...

**Comment by labrys** [comment]
@clinton-hall Sorry was omw home from work.  I'll push further changes to nightly.  Good catch, I missed that one as I run the script from within SAB so it found six in my site-packages.  I had assumed the path extension was  being done from the files in `/*.py`.  Personally I like to do the path extension in it's own separate module, then do something like `import libs` that brings that path into the namespace.  This gives you the flexibility to run with or without the local libraries with the use of a single import.  If you so desire, the `libs` module can then be easily extended for additional functionality (e.g. command line arguments to enable/disable locals on a per library basis).

**Comment by clinton-hall** [comment]
This PATH extension was just my first solution to allow these Libs to be included.
What is involved in putting the path extension in a separate module?

**Comment by labrys** [comment]
At its most basic just put your existing code:
```python
# init libs
PROGRAM_DIR = os.path.dirname(os.path.normpath(os.path.abspath(os.path.join(__file__, os.pardir))))
LIBS_DIR = os.path.join(PROGRAM_DIR, 'libs')
sys.path.insert(0, LIBS_DIR)
```
And of course make sure that that module is imported before any library that requires it.

Also, while looking into the Python 3 compatibility of the libraries, there's some good news: All are available as Python 3 libraries already.  Unfortunately a couple packages have slight differences between the Python 2 and 3 versions (`beautifulsoup4` for one).  These could be standardized to make a single Python 2/3 compatible library.  The advantage would be a single library that works for both, the disadvantage being any library updates, you would have to re-evaluate and re-apply any changes.  However there's a simple solution that doesn't require changes to the library.  Modify the above:
```python
# init libs
PROGRAM_DIR = os.path.dirname(os.path.normpath(os.path.abspath(os.path.join(__file__, os.pardir))))
LIBS_DIR = os.path.join(PROGRAM_DIR, 'libs' if PY2 else 'libs3')
sys.path.insert(0, LIBS_DIR)
```
or if you wanted to avoid duplication of the compatible libraries:
```python
PROGRAM_DIR = os.path.dirname(os.path.normpath(os.path.abspath(os.path.join(__file__, os.pardir))))
LIBS_DIR = os.path.join(PROGRAM_DIR, 'libs')
LIBS2_DIR = os.path.join(PROGRAM_DIR, 'libs2')  # python 2 libraries    
LIBS3_DIR = os.path.join(PROGRAM_DIR, 'libs3')  # python 3 libraries    
sys.path.insert(0, LIBS_DIR)  # Compatible libraries
sys.path.insert(0, LIBS2_DIR if PY2 else LIBS3_DIR)  # Version specific libraries
```

**Pull request merged**
