### PR TITLE
WIP: Adjust fork detection for force_next and change to proc_dir (fork SIC…

### PR DESCRIPTION
**Pull request by miigotu**
…KRAGE was never detected anymore anyways, so I reused that one)

### CODE REVIEW

**Comment by miigotu** [comment]
Didnt know you had updated it so fast ha

**Comment by clinton-hall** [comment]
I'm going to cherry pick these changes anyway... I wasn't sure if these fields were visible (and therefore work in autofork) but I'll add this to autofork along with the new process_directory

**Comment by miigotu** [comment]
I didnt finish this, but I can if you want me to

**Comment by clinton-hall** [comment]
I believe everything should be ok.
Looks like the other part you were adding was an option to force_next, and just do periodic scans of the folder when this is not used?

**Comment by miigotu** [comment]
Mostly I wanted to update the fork detection. In this PR I put process_directory but actually the param I wanted to change SR to was `process_path` and I wanted to get it into n2m before I changed it in SR but its nbd.

These are the current params:
```python
   def processEpisode(self, proc_dir=None, nzbName=None, quiet=None, process_method=None, force=None,
                       is_priority=None, delete_on="0", failed="0", proc_type="auto", force_next=False, *args_, **kwargs):
```

I wanted to rename proc_dir to process_path, delete_on to just delete, and change proc_type to process_mode and maybe add that to nzbtomedia

Mostly the goal is to get the fork detection locked in and at the same time rename all of the params I would like to change when I rewrite the pp.  I plan to incorporate some of the features you have in n2m like checking/pausing/removing torrents/nzb from clients.  The current post processor is just a mess and has at least 10 times the code that is actually necessary to process files.

**Comment by clinton-hall** [comment]
Cool... Anything I can do just let me know...
Changing parameters in n2m is easy. just let me know when you push these in and I'll update them.

As far as features in n2m, please ask if you need help deciphering anything I have done (as I am first to acknowledge that no everything I have done is obvious, efficent, or easy to follow) ;)

**Pull request closed without merging**
