### PR TITLE
Code cleanup autoprocess

### PR DESCRIPTION
**Pull request by labrys**
##### DESCRIPTION
This PR focuses on code clean-up of `core/autoProcess/*`  If you prefer this PR can be split into a bunch of separate smaller PR's or squashed into a single commit.  

While the majority of this PR is just code cleanup for things like PEP8 compliance, the important commits are the following:

##### IMPORTANT CHANGE LIST:
* b7c7ec0 Add missing `os` import
* c7defa3 Fix faulty logic in conditional
* 8880d11 Too broad exceptions.
 * Use `.get()` with default value instead.
 * Use `ValueError` to catch `JSONDecodeError` from `simplejson` and `ValueError` from `json` standard lib
 * Use `request.RequestException` instead.
* 4a40871 Python 3: Convert `except ExceptionClass, Target:` to `except ExceptionClass as Target:`
* 88c9d74 Fix log messages:
 * Renamed undefined `url1` to existing `url` argument
 * Added missing `section` argument to `CDH`
 * Removed undefined variable `good_files`

##### REMAINING CHANGE LIST:
* Add encoding declaration
* Remove unused imports, unused variables, and redundant parentheses
* Fix spelling
* Convert to new-style class by inheriting from `object`
* PEP8: Fix formatting
 * Remove redundant backslash between brackets
 * Fix multiple statements on one line
 * Fix missing/excess whitespace
 * Fix comments not starting with a single `#` and a space
 * Convert tabs to spaces
* PEP8: Test for membership should be 'not in'
* PEP8: comparison to `None` should be 'if cond is not None:'
* PEP8: `.has_key()` is deprecated, use 'in'
* Replace assignment with augmented assignment
* Rewrite dictionary creation as a dictionary literal
* Streamline variable assignment
* Use `format()` instead of `%` for string formatting

### CODE REVIEW

**Comment by clinton-hall** [comment]
Thanks for all the work here. Very thorough clean-up.

Just curious regarding the comment `4a40871 Python 3: Convert except ExceptionClass, Target: to except ExceptionClass as Target:` Do you know how much additional work is required to make this project Python 3 compatible? I tried looking at this a few years back but I don't have any experience with Python 3.

**Comment by labrys** [comment]
I'm in progress of converting all the nzbToMedia, the greater problem might be the libs, I haven't yet looked through those.

**Comment by labrys** [comment]
Things I'm currently aware of (excluding libs) that need to be done for Python 3 compatibility:

Changed in Python 3:
* some standard lib imports have moved
* no `long`
* no `dict.iteritems`
* print is a function
* no `basestring`
* no `unicode`
* checking `isinstance` for int, long, str, unicode, basestring all need to be re-evaluated

**Comment by clinton-hall** [comment]
and then the issue is also keeping backward compatibility with Python 2.7...
I'll need to set up some python 3 test systems and start playing ;)

**Comment by labrys** [comment]
All of those changes can easily be made backwards compatible with Python 2.7

**Pull request merged**
