### PR TITLE
Libs/requirements

### PR DESCRIPTION
**Pull request by labrys**
Add requirements files for an easy way to update dependencies
```
pip install --target libs -r requirements.txt
```

### CODE REVIEW

**Comment by clinton-hall** [comment]
@labrys 
You have been busy.
Thanks for all the work on this. From what I can see (at a quick read) you have updated all libs, improved the imports, made everything Python 3 compatible, and added some auto-import?

Just a few things I wanted to check:

- You are keeping every thing bacwards compatible with Python 2.7.X?
- All Required libs are still included so Posix systems without import tools/compilers (e.g. Nas, busybox etc) will still be able to run?

I think the answer to both is Yes, but just wanted to check.

**Comment by labrys** [comment]
I have made every effort to keep it fully backwards compatible.  
My current daily driver is not running Python 2 but I have done basic testing with Python 2.

I am running the following with Python 3: 
- SABNZBd
- nzbToMedia
- Stheno (a full Python 3 fork of Medusa)

I am running the following with Python 2:
- CouchPotato (although nzbToMedia is still being called by SAB with Python 3)

I do not have a Posix system without import tools/compilers to test on but all the libs are still vendored with nzbToMedia so they should not be impacted.  

In #1429 as part of the libs refactoring I have moved the `sys.path` importing from `core` to the `libs` directory.  This should not represent an issue for those systems.

**Comment by clinton-hall** [comment]
ok, so with a bit of testing on my NAS...

Initially, failed with:
```
    import beets
  File "/volume1/Public/test/nzbToMedia/libs/common/beets/__init__.py", line 20, in <module>
    from beets.util import confit
  File "/volume1/Public/test/nzbToMedia/libs/common/beets/util/confit.py", line 24, in <module>
    import yaml
  File "/volume1/Public/test/nzbToMedia/libs/common/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

I made a quick fix in `common/yaml/__init__.py`
```
diff --git a/libs/common/yaml/__init__.py b/libs/common/yaml/__init__.py
index 9e35fe2..80582dd 100644
--- a/libs/common/yaml/__init__.py
+++ b/libs/common/yaml/__init__.py
@@ -16,6 +16,7 @@ except ImportError:
     __with_libyaml__ = False

 import io
+import six

 def scan(stream, Loader=Loader):
     """
@@ -281,7 +282,7 @@ class YAMLObjectMetaclass(type):
             cls.yaml_loader.add_constructor(cls.yaml_tag, cls.from_yaml)
             cls.yaml_dumper.add_representer(cls, cls.to_yaml)

-class YAMLObject(metaclass=YAMLObjectMetaclass):
+class YAMLObject(six.with_metaclass(YAMLObjectMetaclass)):
     """
     An object that can dump itself to a YAML stream
     and load itself from a YAML stream.
```

Now I am having an issue with the regex in the yaml reader.
```
    from beets.util import confit
  File "/volume1/Public/test/nzbToMedia/libs/common/beets/util/confit.py", line 24, in <module>
    import yaml
  File "/volume1/Public/test/nzbToMedia/libs/common/yaml/__init__.py", line 8, in <module>
    from .loader import *
  File "/volume1/Public/test/nzbToMedia/libs/common/yaml/loader.py", line 4, in <module>
    from .reader import *
  File "/volume1/Public/test/nzbToMedia/libs/common/yaml/reader.py", line 45, in <module>
    class Reader(object):
  File "/volume1/Public/test/nzbToMedia/libs/common/yaml/reader.py", line 137, in Reader
    NON_PRINTABLE = re.compile('[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "/usr/local/AppCentral/python/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/AppCentral/python/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
```

**Comment by clinton-hall** [comment]
I also note the built in git updater appears to not remove the removed directories.... 
I think we need to add in 
`git clean -fd` after the git pull?

**Comment by labrys** [comment]
This is exactly my concern with the lib updates and why I couldn't say with a high degree of confidence that there wouldn't be issues.  The plus side is that the import machinery I have implemented can handle these situations by having the appropriate package in the corresponding folder.

Part of the problem lies in packages that don't make an effort to write compatible code and instead rely on tools such as 2to3.  This creates a package that must be installed using the target python version.  For the initial pass used Python 3.7 to install the common libs.  Some packages may require vendoring via Python 2.7.

Can I assume your NAS is running Python 2.7?

**Comment by clinton-hall** [comment]
Yes, my NAS (actually I have a few different models) all have Python 2.7.X
None of them have (native) compilers so PIP and other library import tools only work where no compiling is required, or if there is a pre-compiled package available.

**Comment by labrys** [comment]
When vendoring libs I prefer to avoid PIP as much as possible since not all systems are guaranteed to have it available.

However, I am strongly considering using PIP for installing windows-specific dependencies as they are larger and (particularly for pywin32) require version-specific installs.  As all supported python versions come with PIP bundled in the Windows install, this should not be an issue.  The `libs.util` framework I added already has a PIP install function for this type of use-case.

Eventually I think it would be best to have a PIP-installable nzbtomedia package that PIP installs all required dependencies.  A separate nzbtomedia-portable package would also be provided which includes vendored libraries (only difference at that time should be the inclusion of the `libs` folder).

**Pull request merged**
