### PR TITLE
Update SickRage dir. Fixes #895

### LINKED ISSUE #895: Sickrage wrong process_dir
LS,

I've noticed that nzbToMedia doesn't work correctly with SickRage.

The problem i noticed is that the http_post_variable for the episode directory is 'dir' but for SickRack this should be 'proc_dir'.

This change was made in the following SickRage commit:
https://github.com/SiCKRAGETV/SickRage/commit/9736515c72e16854353f6874b4f227b248658812

### PR DESCRIPTION
**Pull request by kri99**

### CODE REVIEW

**Comment by n00kie** [comment]
Have manually applied this changes and its fixed sickrage post proc for me. Recommend release.

Thanks kri99

**Comment by frriction** [comment]
sickrage team has split now there are two repo. 
Old one https://github.com/SiCKRAGETV/SickRage only run by echel0n and this pull request goes to this repo only
New one https://github.com/SickRage/SickRage run by whole other team.

read more about it here http://goo.gl/gWWiIc

**Comment by kri99** [comment]
Ok,

So SiCKRAGETV uses 'proc_dir' while SickRage still uses 'dir'.

options:
- make two forks, sickrage + sickragetv and based on the fork send the correct post variable
- send both dir and proc_dir so it works with both

**Comment by clinton-hall** [comment]
Thanks @kri99 
Been a bit busy of late, so I'm still trying to get my head around the 2 x sirckrage branches... The joy of opensource...

**Pull request merged**
