### PR TITLE
improve tests

### PR DESCRIPTION
**Pull request by clinton-hall**

### CODE REVIEW

**Comment by clinton-hall** [comment]
@labrys 

Not saying it is anywhere near perfect, but this no longer uses pip to install requirements, and it tests all imports, ability to initialize, and read a parameter from config....

I added in an import of core before the initialize as each test appears to be isolates (not a "global" import). We do test this import first, so no big drams, but not sure if this should be bundled up within the def test_initial(): and then again within def test_core_parameters():?? this would sound like wasted resources to keep re-doing?

but, as it is, this tests that each module can be imported in 4 python versions.... so that is a big step forward in my opinion.

Is it relatively easy to set the pipeline script to import ffmpeg and test the check_video function etc?

**Comment by labrys** [comment]
Repeating imports for every function has virtually no impact performance... think of import statements as saying "import if not already imported".  

A reason for having the imports within the test case is to allow only the tests that rely on that import to fail and allow the other tests to pass.  For example if a change to the logger caused it to fail to import, at line 41 of `test_initialize.py` none of the tests in `test_initialize.py` would run.

The main benefit to asserting for the imports is clarity.  If you `assert comics in core.auto_process` its explicitly stating that you are looking to see if `core.auto_process` contains `comics`.  If you only import to test, then when someone else looks at the test in the future they might see that its unused and remove it thinking its unnecessary.

Normally you likely would not test imports explicitly, as you will be testing the functionality of the contents of each module imported, however with few tests written its a quick and simple way of providing at least a basic check until the code can be refactored for easier testing.

As for ffmpeg (and nearly all other functionality) it would fall under other tests within other `test_*.py` files.  I would need to look into how it was used within code to see how easy those functions would be to test.  Likely we would need to provide test video files for testing ffmpeg functionality.  I would likely keep those in a separate git repo (e.g. nzbToMedia-testdata) that gets cloned during testing to avoid it being part of the standard git install.

Ideally a coverage tool will also be used during automated testing to see what percentage of the code is covered by tests and point out which code paths aren't.  100% coverage may not be possible, but the goal should be to get as close to 100% coverage as practical.

**Comment by clinton-hall** [comment]
thanks for taking the time to explain this.

regarding a test video... already included as part of the repository (it is a very small video) under tests. I added this a while back to prevent false corrupt video reporting due to a users ffmpegs not being functional.

So with the corruption checks, it first parses the test video through ffprobe, and only if it passes will it then use ffprobe to check the downloaded video.

of course, new codecs could see new videos flagged.

**Comment by labrys** [comment]
An important part of testing though is to also test for other cases... for example testing that a corrupt video actually fails.  Checking multiple video types work.  Checking that a large video does not fail, etc.  The more videos you add to cover test cases, the more likely you would want to separate them from the main repo.

**Comment by clinton-hall** [comment]
Yes, agreed... there is a lot more that needs to be done.
The existing file was simply there to test the ffmpeg functionality on the user's setup.
For CI testing, if we were to test the video check modules, we could test various video. But what I was trying to avoid was having to check a whole library of videos on the user's system.

**Pull request merged**
