### PR TITLE
Typo - qBittorren

### PR DESCRIPTION
**Pull request by boredazfcuk**
qBittorrenHost to qBittorrentHost

I'm running a script on a SABnzbd container to configure nzbToMedia at startup. Spent longer than I should have wondering why:
```
sed -i "s/qBittorrentHost =.*/qBittorrentHost = ${HOSTNAME}/" /nzbToMedia/autoProcessMedia.cfg
```
wasn't working.

### CODE REVIEW

**Comment by clinton-hall** [comment]
Thanks... Because this typo has existed for a while, I need to fix this at the other end (i.e. when the script reads the value from the .cfg) and I have added a migration so that existing users don't have to add the new value...

**Comment by clinton-hall** [comment]
Merged into nightly....
I'm hoping to test everything and merge up to master soon, but for now this is only in nightly branch.

**Comment by boredazfcuk** [comment]
> 
> 
> Thanks... Because this typo has existed for a while, I need to fix this at the other end (i.e. when the script reads the value from the .cfg) and I have added a migration so that existing users don't have to add the new value...

Sorry, I should have thought to check the rest of the project. My bad.

**Comment by clinton-hall** [comment]
All good... hopefully all fixed now.

**Pull request merged**
